name             'WebSphereBPM'
maintainer       'Rohit Gabriel'
maintainer_email 'rohit.phoenix@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures WebSphereBPM'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.2'
#depends			 'InstallationManager'
#depends			 'FTPlogin'
#depends			 'db2'
