name             'WebSphereAS85'
maintainer       'rohit company'
maintainer_email 'rohit.phoenix@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures WebSphereAS85'
version          '1.0.0'
