name 'mymq'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures mymq'
long_description 'Installs/Configures mymq'
version '0.1.0'
depends 'ibm_mq'
depends 'apt'