
default['WebSphereBPM']['was_install_dir'] = '/opt/IBM/WebSphere'
default['WebSphereBPM']['imshared_install_dir'] = 'opt/IBM/IMShared'
default['WebSphereBPM']['imcl_install_dir'] = '/opt/IBM/InstallationManager'
default['WebSphereBPM']['imagentdata_install_dir'] = '/opt/IBM/IMAgentData'
default['WebSphereBPM']['package-name-1'] = 'BPM_Adv_V855_Linux_x86_1_of_3.tar.gz'
default['WebSphereBPM']['package-name-2'] = 'BPM_Adv_V855_Linux_x86_2_of_3.tar.gz'
default['WebSphereBPM']['package-name-3'] = 'BPM_Adv_V855_Linux_x86_3_of_3.tar.gz'
default['WebSphereBPM']['package1-sha256sum'] = 'd065493340e830ded1eb1f7e29a851292447d234348c50da9d37017473ef71ed'
default['WebSphereBPM']['package2-sha256sum'] = '049a774ff4704ca06001185875307f2eba3bb97e4082d16c871e89dddaa05abe'
default['WebSphereBPM']['package3-sha256sum'] = '778d5d9ef80b0aac20e928be8f2858ce6478cc2da2e31ee2686b2ea5a204aba9'
default['WebSphereBPM']['binaryhost'] = '192.168.1.7'
default['WebSphereBPM']['bpmuser'] = 'bpmuser'
default['WebSphereBPM']['bpmgroup'] = 'wasgrp'
default['WebSphereBPM']['bpmuserhome'] = '/home/bpmuser'
default['WebSphereBPM']['ftploginuser'] = 'ftplogin'
default['WebSphereBPM']['ftppath'] = '/opt/ibm/HTTPServer/docroot'
default['WebSphereBPM']['bpm-responsefile'] = 'BPM-responsefile.xml'
default['WebSphereBPM']['bpm-installpath'] = '/opt/IBM/WebSphere/BPM/v8.5'
default['WebSphereBPM']['imcl-path'] = '/opt/IBM/InstallationManager/eclipse/tools/imcl'
default['WebSphereBPM']['bpm-path'] = '/opt/IBM/WebSphere/BPM/v8.5/bin'
default['WebSphereBPM']['bpmdmgrbin'] = '/opt/IBM/WebSphere/BPM/v8.5/profiles/Dmgr/bin'



default['WebSphereBPM']['db2password'] = 'W1zplay11'
default['WebSphereBPM']['bpmuser'] = 'bpmadmin'
default['WebSphereBPM']['bpmpassword'] = 'W1zplay11'

default['WebSphereBPM']['Advanced-PS-ThreeClusters-DB2-props'] = 'Advanced-PS-ThreeClusters-DB2.properties'
default['WebSphereBPM']['bpmdmgrnodename'] = 'DMGRNode'
default['WebSphereBPM']['bpmcellname'] = 'BPMCell'
default['WebSphereBPM']['bpmdmgrpath'] = '/opt/IBM/WebSphere/BPM/v8.5/profiles/Dmgr'
default['WebSphereBPM']['bpmdmgrname'] = 'Dmgr'
default['WebSphereBPM']['bpmdmgrsoapport'] = '8879'
default['WebSphereBPM']['bpmnodename'] = 'ManagedAppServers'
