name             'InstallationManager'
maintainer       'Rohit Gabriel'
maintainer_email 'rohit.phoenix@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures IBM InstallationManager'
long_description 'Installs/Configures IBM InstallationManager'
version          '0.1.1'
